from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import List, Protocol, Tuple, Optional, Dict


@dataclass
class Paths:
    base: Path              # wave base or global base for queue dirs
    open: Path
    blocked: Path
    claimed: Path
    closed: Path
    failed: Path
    dead: Path
    raw: Path               # always global under .slaps/tasks/raw
    admin: Path             # always global under .slaps/tasks/admin
    admin_closed: Path
    edges_csv: Path
    failure_reasons: Path
    attempts: Path


class FilePort(Protocol):
    def mkdirs(self, d: Path) -> None: ...
    def list_files(self, d: Path) -> List[Path]: ...
    def read_text(self, p: Path) -> str: ...
    def write_text(self, p: Path, text: str) -> None: ...
    def append_text(self, p: Path, text: str) -> None: ...
    def move_atomic(self, src: Path, dst: Path) -> bool: ...
    def exists(self, p: Path) -> bool: ...


class LLMPort(Protocol):
    def exec(self, prompt: str, timeout: float | None = None, out_path: Path | None = None, err_path: Path | None = None) -> Tuple[int, str, str]: ...  # rc, stdout, stderr


class SleepPort(Protocol):
    def sleep(self, seconds: float) -> None: ...


class ReporterPort(Protocol):
    def report(self, text: str) -> None: ...


# ----------------------------- GH Integration Ports -----------------------------

@dataclass
class GHProject:
    owner: str
    number: int
    id: str  # GraphQL node id
    title: str


@dataclass
class GHField:
    id: str
    name: str
    data_type: str  # TEXT | SINGLE_SELECT | DATE | NUMBER
    options: Dict[str, str] | None = None  # for SINGLE_SELECT: name -> option_id


class GHPort(Protocol):
    def ensure_project(self, title: str) -> GHProject: ...
    def ensure_labels(self, labels: List[str]) -> None: ...
    def ensure_fields(self, project: GHProject, single_select_state_values: List[str]) -> Dict[str, GHField]: ...
    def repo_owner(self) -> str: ...
    def issue_node_id(self, issue_number: int) -> str: ...
    def ensure_issue_in_project(self, project: GHProject, issue_number: int) -> str: ...  # returns item_id
    def list_items(self, project: GHProject) -> List[dict]: ...  # raw items JSON
    def set_item_number_field(self, project: GHProject, item_id: str, field: GHField, value: float) -> None: ...
    def set_item_text_field(self, project: GHProject, item_id: str, field: GHField, value: str) -> None: ...
    def set_item_single_select(self, project: GHProject, item_id: str, field: GHField, option_value: str) -> None: ...
    def get_item_fields(self, project: GHProject, item_id: str) -> Dict[str, str]: ...  # field name -> stringified value
    def find_item_by_issue(self, project: GHProject, issue_number: int) -> Optional[str]: ...
    def add_label(self, issue_number: int, label: str) -> None: ...
    def remove_label(self, issue_number: int, label: str) -> None: ...
    def add_comment(self, issue_number: int, body_markdown: str) -> None: ...
    def list_issue_comments(self, issue_number: int) -> List[dict]: ...  # [{createdAt, body}]
    def fetch_issue_json(self, issue_number: int) -> dict: ...  # minimal GH JSON
    def project_item_create_draft(self, project: GHProject, title: str, body: str) -> str: ...  # returns item id
    def repo_name(self) -> str: ...
    def list_items(self, project: GHProject) -> List[dict]: ...
    def list_issues_for_wave(self, wave: int) -> List[int]: ...
    def get_blockers(self, issue_number: int) -> List[int]: ...
    def get_issue_wave_by_label(self, issue_number: int) -> int | None: ...
    def create_issue(self, title: str, body: str) -> int: ...
